# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: fe2023
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: shui
# "service" is the name of this project. This will also be added to your AWS resource names.
service: Shui

provider:
  name: aws
  runtime: nodejs18.x
  deploymentMethod: direct
  region: eu-north-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
          Resource: arn:aws:dynamodb:${aws:region}:*:table/Shui

functions:
  hello:
    handler: createMessage.createMessage
    events:
      - httpApi:
          path: /createMessage
          method: post

resources:
  Resources:
    TodoTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Shui
        AttributeDefinitions:
          - AttributeName: "shuiId"
            AttributeType: "S"
          - AttributeName: "timeStamp"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "shuiId"
            KeyType: HASH
          - AttributeName: "timeStamp"
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
