# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: fe2023
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: shui
# "service" is the name of this project. This will also be added to your AWS resource names.
service: Shui

provider:
  name: aws
  runtime: nodejs18.x
  deploymentMethod: direct
  region: eu-north-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
          Resource: arn:aws:dynamodb:${aws:region}:*:table/Shui-border

functions:
  hello:
    handler: functions/createMessage.createMessage
    events:
      - httpApi:
          path: /createMessage
          method: post

  FetchMessages:
    handler: functions/fetchMessages.fetchMessages
    events:
      - httpApi:
          path: /fetchMessages
          method: get

  ChangeMessage:
    handler: functions/changeMessage.changeMessage
    events:
      - httpApi:
          path: /changeMessage/{shuiId}
          method: put

resources:
  Resources:
    TodoTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Shui-border
        AttributeDefinitions:
          - AttributeName: "shuiId"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "shuiId"
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
